"""
main_isaac/main.py
==================
여러 로봇을 단일 창고 환경에서 동시 구동하는 진입점.

실행:
    python /path/to/main_isaac/main.py
    또는
    cd /path/to/main_isaac && python main.py

로봇 추가 방법:
    1. robot_config.py 의 ROBOT_REGISTRY 에 항목 추가
    2. 새 로봇 타입이면 robots/ 에 에이전트 클래스 작성 후 _AGENT_CLASSES 에 등록
"""
import os, sys

# Isaac Sim 내장 ROS2 (Python 3.11용) 경로 설정.
# LD_LIBRARY_PATH는 프로세스 시작 전에만 적용되므로,
# 미설정 시 환경변수를 추가하고 자신을 재실행한다.
_BRIDGE = "/home/rokey/dev_ws/isaac_sim/isaacsim/_build/linux-x86_64/release/exts/isaacsim.ros2.bridge/humble"
if os.path.isdir(_BRIDGE) and _BRIDGE + "/lib" not in os.environ.get("LD_LIBRARY_PATH", ""):
    _env = os.environ.copy()
    _env["LD_LIBRARY_PATH"] = _BRIDGE + "/lib:" + _env.get("LD_LIBRARY_PATH", "")
    _env["PYTHONPATH"]      = _BRIDGE + "/rclpy:" + _env.get("PYTHONPATH", "")
    _env["ROS_DISTRO"]      = "humble"
    _env["RMW_IMPLEMENTATION"] = "rmw_fastrtps_cpp"
    os.execve(sys.executable, [sys.executable] + sys.argv, _env)

from isaacsim import SimulationApp

simulation_app = SimulationApp({
    "headless": False,
    "exts": [
        "omni.isaac.ros2_bridge",
        "omni.isaac.core_nodes",
        "omni.graph.action",
        "isaacsim.robot_setup.assembler",
        "isaacsim.robot.wheeled_robots",
    ],
})

import sys
import os

# main_isaac/ 디렉토리를 sys.path 에 추가 → 어느 경로에서 실행해도 로컬 모듈 인식
_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)
_IWHUB_MOVEMENT_SRC = os.path.join(_HERE, "robots", "iw_hub", "src", "iw_hub_movement")
if _IWHUB_MOVEMENT_SRC not in sys.path:
    sys.path.insert(0, _IWHUB_MOVEMENT_SRC)

import time
import math
import threading
import carb
import omni.kit.app
from isaacsim.core.api import World

from robot_config import PHYSICS_DT, RENDERING_DT, ROBOT_REGISTRY
from world_setup import setup_warehouse, BoxSpawner
from path_planner import init_planner
from control_center import ControlCenter
from minimap import Minimap

#########################################################로봇 추가 부분
from robots.spot.spot_agent       import SpotAgent
from robots.m0609.m0609_agent     import M0609Agent
from robots.drone.drone_agent     import DroneAgent
from robots.iw_hub.iw_hub_agent   import IwHubAgent
#####################################################################

# ── 새 로봇 타입을 추가하면 여기에 등록 ────────────────────────────────
_AGENT_CLASSES = {

    ##############################바로 위에서 추가한 부분을 불러오고 이름을 지정합니다
    "spot"  : SpotAgent,
    "m0609" : M0609Agent,
    "drone" : DroneAgent,
    "iw_hub": IwHubAgent,
    # iw_hub_03 uses the same class — registry key is already "iw_hub"
    ########################################################################
}


class IwHubInlineConsole:
    """Manual console that controls the live iw_hub agent directly."""

    def __init__(self, agent):
        self.agent = agent
        self._stop = threading.Event()
        self._records = []
        self._thread = threading.Thread(target=self._loop, daemon=True)
        self._default_linear = 0.25
        self._default_angular = 0.5

    def start(self):
        self._thread.start()
        print("[main] IW Hub inline console started. Type 'help' in this terminal.")

    def close(self):
        self._stop.set()
        try:
            self.agent._publish_cmd_vel(0.0, 0.0)
        except Exception:
            pass

    def _pose(self):
        try:
            return self.agent._get_xy_hdg()
        except Exception:
            return self.agent.get_world_xy()

    def _print_help(self):
        print(
            "\nIW Hub inline console commands:\n"
            "  f [speed]        forward\n"
            "  b [speed]        backward\n"
            "  left [speed]     turn left\n"
            "  right [speed]    turn right\n"
            "  stop             stop wheels\n"
            "  auto             resume autonomous FSM\n"
            "  up               lift up\n"
            "  down             lift down\n"
            "  lift <height>    set lift height\n"
            "  pose             print current minimap pose\n"
            "  rec [name]       record current minimap pose\n"
            "  list             list recorded poses\n"
            "  save_py [path]   save recorded poses as Python list\n"
            "  quit             close console input thread\n"
        )

    def _record(self, name):
        x, y, yaw = self._pose()
        self._records.append({
            "name": name,
            "x": float(x),
            "y": float(y),
            "yaw": float(yaw),
        })
        print(f"[iw-hub-console] recorded {name}: ({x:.3f}, {y:.3f}) yaw={math.degrees(yaw):.1f}deg")

    def _save_py(self, path):
        lines = [
            "# Generated by main.py IW Hub inline console",
            f"ROBOT_NAME = {self.agent.name!r}",
            "WAYPOINTS = [",
        ]
        for rec in self._records:
            lines.append(f"    ({rec['name']!r}, {rec['x']:.4f}, {rec['y']:.4f}, {math.degrees(rec['yaw']):.2f}),")
        lines.append("]")
        lines.append("")
        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        print(f"[iw-hub-console] saved {path}")

    def _loop(self):
        print("iw-hub> ", end="", flush=True)
        while not self._stop.is_set():
            try:
                raw = input().strip()
            except EOFError:
                break
            except KeyboardInterrupt:
                self.close()
                break

            if not raw:
                print("iw-hub> ", end="", flush=True)
                continue

            parts = raw.split()
            cmd = parts[0].lower()
            try:
                speed = float(parts[1]) if len(parts) > 1 else None
                if cmd in ("q", "quit", "exit"):
                    self.close()
                    break
                elif cmd in ("h", "help"):
                    self._print_help()
                elif cmd in ("f", "forward"):
                    self.agent._manual_override = True
                    self.agent._publish_cmd_vel(speed if speed is not None else self._default_linear, 0.0)
                elif cmd in ("b", "back", "backward"):
                    self.agent._manual_override = True
                    self.agent._publish_cmd_vel(-(speed if speed is not None else self._default_linear), 0.0)
                elif cmd == "left":
                    self.agent._manual_override = True
                    self.agent._publish_cmd_vel(0.0, speed if speed is not None else self._default_angular)
                elif cmd == "right":
                    self.agent._manual_override = True
                    self.agent._publish_cmd_vel(0.0, -(speed if speed is not None else self._default_angular))
                elif cmd in ("s", "stop"):
                    self.agent._manual_override = True
                    self.agent._publish_cmd_vel(0.0, 0.0)
                elif cmd == "auto":
                    self.agent._publish_cmd_vel(0.0, 0.0)
                    self.agent._manual_override = False
                    print("[iw-hub-console] autonomous FSM resumed")
                elif cmd == "up":
                    self.agent._manual_override = True
                    self.agent._publish_lift(self.agent.LIFT_UP)
                elif cmd == "down":
                    self.agent._manual_override = True
                    self.agent._publish_lift(0.0)
                elif cmd == "lift":
                    self.agent._manual_override = True
                    self.agent._publish_lift(float(parts[1]))
                elif cmd == "pose":
                    x, y, yaw = self._pose()
                    print(f"[iw-hub-console] minimap pose=({x:.3f}, {y:.3f}) yaw={math.degrees(yaw):.1f}deg")
                elif cmd in ("rec", "record"):
                    name = parts[1] if len(parts) > 1 else f"p{len(self._records) + 1:02d}"
                    self._record(name)
                elif cmd == "list":
                    for idx, rec in enumerate(self._records, 1):
                        print(f"{idx:02d}. {rec['name']}: ({rec['x']:.3f}, {rec['y']:.3f}) yaw={math.degrees(rec['yaw']):.1f}deg")
                elif cmd == "save_py":
                    path = parts[1] if len(parts) > 1 else "iw_hub_waypoints.py"
                    self._save_py(path)
                else:
                    print(f"[iw-hub-console] unknown command: {cmd}. Type help.")
            except Exception as e:
                print(f"[iw-hub-console] command error: {e}")
            print("iw-hub> ", end="", flush=True)

# ── 월드 생성 ─────────────────────────────────────────────────────────
my_world = World(
    stage_units_in_meters=1.0,
    physics_dt=PHYSICS_DT,
    rendering_dt=RENDERING_DT,
)

setup_warehouse(my_world)

# ── USD 로드 대기 ─────────────────────────────────────────────────────
print("[main] 씬 로드 중...")
for _ in range(300):
    omni.kit.app.get_app().update()
time.sleep(1.0)

# ── 에이전트 생성 + setup ────────────────────────────────────────────
agents = []
for cfg in ROBOT_REGISTRY:
    robot_type = cfg["type"]
    if robot_type not in _AGENT_CLASSES:
        raise ValueError(f"알 수 없는 로봇 타입: '{robot_type}'  "
                         f"(등록된 타입: {list(_AGENT_CLASSES)})")
    agent = _AGENT_CLASSES[robot_type](cfg, my_world)
    agent.setup()
    agents.append(agent)
    print(f"[main] 에이전트 등록 완료 — {cfg['name']} ({robot_type})  "
          f"spawn={cfg['spawn_xyz']}")

print(f"\n[main] 총 {len(agents)}개 로봇 로드 완료\n")

# ── 경로 계획기 초기화 (에이전트 생성 후, 월드 리셋 전) ─────────────────
planner = init_planner(agents)
print(f"[main] 경로 계획기 초기화 완료 — 에이전트 {len(agents)}개 등록")

# ── 월드 리셋 ─────────────────────────────────────────────────────────
my_world.reset()

for _ in range(60):
    omni.kit.app.get_app().update()

for agent in agents:
    agent.post_reset()

manual_console = None
if sys.stdin.isatty() and os.environ.get("DISABLE_IWHUB_CONSOLE", "0") != "1":
    try:
        iw_hub2 = next((a for a in agents if getattr(a, "name", None) == "iw_hub_02"), None)
        if iw_hub2 is None:
            raise RuntimeError("iw_hub_02 agent not found")
        manual_console = IwHubInlineConsole(iw_hub2)
        manual_console.start()
    except Exception as e:
        carb.log_warn(f"[main] IW Hub manual console 시작 실패: {e}")
else:
    print("[main] IW Hub manual console skipped (no TTY or disabled)")

# ── BoxSpawner + ControlCenter + Minimap 초기화 (world.reset() 이후) ──
box_spawner   = BoxSpawner(RENDERING_DT)
control_center = ControlCenter(my_world, agents)
minimap = Minimap(agents)

# ── physics 콜백 ──────────────────────────────────────────────────────
_step_count  = 0
_GLOBAL_WARM = 30   # 전 에이전트 공통 워밍업 (physics 안정 대기)


def _on_physics_step(dt: float) -> None:
    global _step_count
    _step_count += 1
    if _step_count < _GLOBAL_WARM:
        return
    for agent in agents:
        try:
            agent.on_physics_step(dt)
        except Exception as e:
            carb.log_warn(f"[{agent.name}] on_physics_step 오류: {e}")


my_world.add_physics_callback("multi_robot_step", callback_fn=_on_physics_step)

# ── 메인 루프 ─────────────────────────────────────────────────────────
print("[main] 시뮬레이션 시작")
try:
    while simulation_app.is_running():
        my_world.step(render=True)
        for agent in agents:
            agent.on_render_step()
        box_spawner.update()
        control_center.tick()
        minimap.update()
finally:
    if manual_console is not None:
        manual_console.close()
    minimap.close()
    control_center.close()
    my_world.clear()
    simulation_app.close()
    print("[main] 시뮬레이션 종료.")
